In [2]:
import numpy as np

In [3]:
# How do you create a NumPy array from a list?
l = [1,2, 3,4]
np.array(l)

array([1, 2, 3, 4])

In [4]:
# How can you create an array of evenly spaced numbers between two values?
arr1 = np.linspace(1,10,10)
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
# What’s the difference between np.zeros(), np.ones(), and np.empty()?
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
# It random fills any garbage
# Used when values are to be filled immediately afterwards
np.empty(shape=(2,2), dtype=float)

array([[1., 1.],
       [1., 1.]])

In [12]:
# How do you generate a 2D array with random integers between 0 and 100?
np.random.randint(low=1, high=100, size=(2,2))

array([[98, 97],
       [99, 16]])

In [14]:
# What’s the difference between np.array() and np.asarray()?
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [16]:
b = np.asarray(a)
b is a # returns the same copy

True

In [18]:
# What is broadcasting in NumPy? Give an example.
a= np.array([1,2,3])
b = np.array([1])
a+b

array([2, 3, 4])

In [19]:
# Explain the difference between reshape() and ravel() in NumPy.
a = np.array([[2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [20]:
a.ravel()

array([2, 3, 4, 5])

In [22]:
a.reshape((1,4))

array([[2, 3, 4, 5]])

In [25]:
# How do you find the shape, size, and data type of a NumPy array?
a.dtype, a.shape, a.size

(dtype('int32'), (2, 2), 4)

In [28]:
# What does np.linspace() do? What’s the difference from np.arange()?
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# Create a 4x4 identity matrix using NumPy.
a = np.ones(shape=(4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
# Given a 1D array, write code to reverse it using slicing.
a = np.array([1,2,3,4])
a[::-1]

array([4, 3, 2, 1])

In [35]:
# How do you replace all odd numbers in a NumPy array with -1?
np.where(a%2==1, -1, a)

array([-1,  2, -1,  4])

In [37]:
# Given a 2D array, how do you flatten it into a 1D array?
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [40]:
# How do you find the indices of non-zero elements in a NumPy array?
a = np.array([0,1,2,0])
a

array([0, 1, 2, 0])

In [41]:
np.where(a !=0)

(array([1, 2], dtype=int64),)

In [49]:
# Write code to normalize a NumPy array (scale values between 0 and 1).
a = np.array([[3,5],
           [4,5]])
a

array([[3, 5],
       [4, 5]])

In [50]:
norm = np.linalg.norm(a, axis=0)

In [52]:
norm

array([5.        , 7.07106781])

In [51]:
a/norm

array([[0.6       , 0.70710678],
       [0.8       , 0.70710678]])

In [53]:
# How do you compute the dot product of two matrices in NumPy?

In [56]:
a = np.array([1,1])
b = np.array([[4],
             [1]])
c = np.array([2,3])

In [55]:
np.dot(a,b)

array([5])

In [58]:
np.dot(a,c)

5

In [59]:
# How do you find the cumulative sum and cumulative product of a NumPy array?
a = np.array([1,2,3,4,5])
a.cumsum()

array([ 1,  3,  6, 10, 15])

In [60]:
a.cumprod()

array([  1,   2,   6,  24, 120])

In [61]:
# How do you create a boolean mask for elements greater than the mean of the array?
a = np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [62]:
np.where(a>a.mean(), True, False)

array([False, False,  True,  True])

In [63]:
# How do you find the most frequent value (mode) in a NumPy array?
a = np.array([1,2,2,2,3,4,4])
a

array([1, 2, 2, 2, 3, 4, 4])

In [64]:
unique, count = np.unique(a, return_counts=True)
unique

array([1, 2, 3, 4])

In [65]:
count

array([1, 3, 1, 2], dtype=int64)

In [66]:
max_arg = np.argmax(count)
max_arg

1

In [68]:
unique[max_arg]

2